# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

#pool:
#  vmImage: ubuntu-latest
pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    sqMavenPluginVersionChoice: 'latest'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarumanzor'
    organization: 'umanzordiplomado'
    scannerMode: 'Other'
    extraProperties: |
        sonar.projectKey=umanzordiplomado
        sonar.projectName=umanzordiplomado

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    goals: clean package -DskipTests
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'sonarumanzor'
    organization: 'umanzordiplomado'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '60'