# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

#pool:
#  vmImage: ubuntu-latest
pool: 
  vmImage: maven:3-jdk-11
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarumanzor'
    organization: 'umanzordiplomado'
    scannerMode: 'Other'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- task: SonarCloudAnalyze@1
  displayName: Sonar
  inputs:
    SonarCloud: 'umanzordiplomado'
    organization: 'umanzordiplomado'
    projectKey: 'umanzordiplomado'
    projectName: 'diplomado'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '60'

